language: python

python:
  - "3.8"  # Specify the Python version you're using

# Commands to install dependencies
install:
  - pip install -r requirements.txt  # Install your dependencies

# Commands to run before your tests (e.g., migrations)
before_script:
  - python manage.py migrate  # Run database migrations

# Command to run tests
script:
  - pytest  # If you're using pytest
  # - python manage.py test  # If you prefer Django's built-in test framework

deploy:
  provider: elasticbeanstalk
  env:
    access_key_id:
      secure: "AKIA3M7ACYCQ3QPKF6X7"
    secret_access_key:
      secure: "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"
  region: "us-east-1"
  app: "SE_project"
  env: "SE-project-dev"
  bucket_name: "elasticbeanstalk-us-east-1-783764603041"
  on:
    branch: main
